#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1

start_service() {
    /usr/bin/generate_proxy_config.sh

    procd_open_instance
    procd_set_param command /usr/bin/proxy_app -config /etc/config/proxy_app.json
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall proxy_app
}