name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest,ubuntu-22.04]
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
          - os: ubuntu-22.04
            goos: linux
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build for ${{ matrix.goos }} ${{ matrix.goarch }}
        run: |
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          go build -o reverse_proxy_${{ matrix.goos }}_${{ matrix.goarch }} main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: reverse_proxy_${{ matrix.goos }}_${{ matrix.goarch }}
          path: reverse_proxy_${{ matrix.goos }}_${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact for Linux AMD64
        uses: actions/download-artifact@v2
        with:
          name: reverse_proxy_linux_amd64
          path: ./dist

      - name: Download artifact for Windows AMD64
        uses: actions/download-artifact@v2
        with:
          name: reverse_proxy_windows_amd64
          path: ./dist

      - name: Download artifact for Linux ARM64
        uses: actions/download-artifact@v2
        with:
          name: reverse_proxy_linux_arm64
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/reverse_proxy_linux_amd64
            dist/reverse_proxy_windows_amd64
            dist/reverse_proxy_linux_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}